### ISSUE TITLE
What promises does blushproof make to its users, and who are they?

### ISSUE THREAD

**Issue by gregglind** [mozilla/blushproof#19]
<insert standard plea for user driven design here>

Were we in UX-Research, we might ask these questions:
1.  Exactly what problems is `blushproof` trying to solve?
2.  What users / scenarios / personas have those problems?
3.  Are those the most important problems to solve for them?  What feature set actually addresses them?

This is a plea to take some thinking time, not just about the technical aspects of how to make this work, but some decisions about how this should work to make people happy!

This is complementary to the technical implementation!

**Comment by monicachew** [comment]
Great question, I hope @mozkeeler chimes in with his own responses.

<ol>
<li> Making private browsing mode more usable, by hinting to the user when they should enter it.
<li> People who would benefit from private browsing, i.e. those vulnerable to shoulder-surfing or share user accounts on the same device
<li> This one is the toughest -- because as we all know, private browsing mode is broken for long-term tasks. It is possible that people do go ahead an login to their favorite sites while in PB mode to do curation and other forms of participation on social networks, etc -- at which point things like encrypted profiles and fast profile switching are the right answer. I don't think we can know the feature set a priori, without iterating on something that at least makes PB mode easier.
</ol>

**Comment by mozkeeler** [comment]
1. The problem of, "I accidentally visited a site in my default profile that I would normally use private browsing for and now I'm embarrassed/don't know how to undo this without just nuking my entire history, which I don't want to do."
2. People who visit sites where they would be embarrassed if their friends/family/coworkers found out.
3. Yes, I think so. Basically, these users have sites they want to visit, but they're worried about them showing up in their history or the awesome bar. They know they can use private browsing, but what happens when they forget to turn it on? Firefox should help the user help themselves in this case.

**Comment by monicachew** [comment]
This is mostly documented in the design doc: https://github.com/mozilla/blushproof/blob/master/doc/designdoc.md
