### ISSUE TITLE
opening a blushy site in a new tab doesn't quite work...

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/blushproof#93]
We might need to be a bit more careful handling things like ctrl+click and open in new tab (and probably even open in new window, but who does that?).

**Comment by monicachew** [comment]
From Tanvi:

(11:57:16 AM) tanvi: actually, command click. when you want to open a new tab and hit an "embarassing page"
(11:57:45 AM) tanvi: example: https://www.google.com/search?q=mozilla+doc+sprint try opening the twitter serach result in a new tab
(11:59:01 AM) tanvi: the google redirect page opens in a new tab, the blushproof ui comes up in the current tab.  clicking use normal window results in navigating to twitter.com in the current tab instead of in the new tab
